/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ButtonMaxll {
    }
}
declare global {
    interface HTMLButtonMaxllElement extends Components.ButtonMaxll, HTMLStencilElement {
    }
    var HTMLButtonMaxllElement: {
        prototype: HTMLButtonMaxllElement;
        new (): HTMLButtonMaxllElement;
    };
    interface HTMLElementTagNameMap {
        "button-maxll": HTMLButtonMaxllElement;
    }
}
declare namespace LocalJSX {
    interface ButtonMaxll {
    }
    interface IntrinsicElements {
        "button-maxll": ButtonMaxll;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "button-maxll": LocalJSX.ButtonMaxll & JSXBase.HTMLAttributes<HTMLButtonMaxllElement>;
        }
    }
}
